[tool.poetry]
name = "time-sync-1"
version = "0.1.0"
description = ""
authors = ["theonlybex <abdimanapovb@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
Django = "^3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
